trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pylint app.py
  displayName: 'Install dependencies and lint'

- script: |
    zip -r app.zip .
  displayName: 'Package application'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'UdacityDS - 66'
    appName: 'udacity-webapp-shivali-july2026'
    package: '$(System.DefaultWorkingDirectory)/app.zip'

