name: Deploy to Azure WebApp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          enable-AzPSSession: false
          allow-no-subscriptions: true

      - name: Deploy using Azure CLI
        run: |
          az webapp deploy \
            --resource-group Azuredevops \
            --name udacity-webapp-shivali \
            --src-path . \
            --type zip
